// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/cuti" | "/admin/dashboard" | "/admin/divisi" | "/admin/employees" | "/admin/employees/[id]" | "/admin/jabatans" | "/admin/kantor" | "/admin/laporan-kehadiran" | "/admin/laporan-kehadiran/[id]" | "/admin/laporan-kehadiran/print" | "/admin/monitor_perusahaan" | "/admin/notifikasi" | "/admin/pengumuman" | "/admin/positions" | "/admin/rekap-kehadiran-karyawan" | "/admin/rekap-kehadiran-karyawan/[id]" | "/admin/shifts" | "/admin/work-schedules" | "/beranda" | "/cuti" | "/history" | "/history/[id]" | "/login" | "/notifikasi" | "/pengumuman" | "/presensi" | "/profil"
type AppRouteHandlerRoutes = "/api/admin/attendance-reports" | "/api/admin/attendance-reports/[id]" | "/api/admin/dashboard" | "/api/admin/departments" | "/api/admin/employee-attendance-recap" | "/api/admin/jabatans" | "/api/admin/leave-requests" | "/api/admin/monitor-perusahaan" | "/api/admin/notifications" | "/api/admin/office-locations" | "/api/admin/offices" | "/api/admin/offices/[id]" | "/api/admin/positions" | "/api/admin/shifts" | "/api/admin/work-schedules" | "/api/announcements" | "/api/attendance/[id]" | "/api/attendance/[id]/photo" | "/api/attendance/check-in" | "/api/attendance/check-out" | "/api/attendance/history" | "/api/attendance/today" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/employees" | "/api/geocode/reverse" | "/api/history" | "/api/leave-requests" | "/api/notifications" | "/api/offices/active" | "/api/profil" | "/api/profil/change-password" | "/api/profil/photo"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/cuti": {}
  "/admin/dashboard": {}
  "/admin/divisi": {}
  "/admin/employees": {}
  "/admin/employees/[id]": { "id": string; }
  "/admin/jabatans": {}
  "/admin/kantor": {}
  "/admin/laporan-kehadiran": {}
  "/admin/laporan-kehadiran/[id]": { "id": string; }
  "/admin/laporan-kehadiran/print": {}
  "/admin/monitor_perusahaan": {}
  "/admin/notifikasi": {}
  "/admin/pengumuman": {}
  "/admin/positions": {}
  "/admin/rekap-kehadiran-karyawan": {}
  "/admin/rekap-kehadiran-karyawan/[id]": { "id": string; }
  "/admin/shifts": {}
  "/admin/work-schedules": {}
  "/api/admin/attendance-reports": {}
  "/api/admin/attendance-reports/[id]": { "id": string; }
  "/api/admin/dashboard": {}
  "/api/admin/departments": {}
  "/api/admin/employee-attendance-recap": {}
  "/api/admin/jabatans": {}
  "/api/admin/leave-requests": {}
  "/api/admin/monitor-perusahaan": {}
  "/api/admin/notifications": {}
  "/api/admin/office-locations": {}
  "/api/admin/offices": {}
  "/api/admin/offices/[id]": { "id": string; }
  "/api/admin/positions": {}
  "/api/admin/shifts": {}
  "/api/admin/work-schedules": {}
  "/api/announcements": {}
  "/api/attendance/[id]": { "id": string; }
  "/api/attendance/[id]/photo": { "id": string; }
  "/api/attendance/check-in": {}
  "/api/attendance/check-out": {}
  "/api/attendance/history": {}
  "/api/attendance/today": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/employees": {}
  "/api/geocode/reverse": {}
  "/api/history": {}
  "/api/leave-requests": {}
  "/api/notifications": {}
  "/api/offices/active": {}
  "/api/profil": {}
  "/api/profil/change-password": {}
  "/api/profil/photo": {}
  "/beranda": {}
  "/cuti": {}
  "/history": {}
  "/history/[id]": { "id": string; }
  "/login": {}
  "/notifikasi": {}
  "/pengumuman": {}
  "/presensi": {}
  "/profil": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
