// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/cuti/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cuti">> = Specific
  const handler = {} as typeof import("../../src/app/admin/cuti/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/divisi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/divisi">> = Specific
  const handler = {} as typeof import("../../src/app/admin/divisi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/employees/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/employees/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/employees">> = Specific
  const handler = {} as typeof import("../../src/app/admin/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/jabatans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jabatans">> = Specific
  const handler = {} as typeof import("../../src/app/admin/jabatans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/kantor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kantor">> = Specific
  const handler = {} as typeof import("../../src/app/admin/kantor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/laporan-kehadiran/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/laporan-kehadiran/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/laporan-kehadiran/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/laporan-kehadiran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/laporan-kehadiran">> = Specific
  const handler = {} as typeof import("../../src/app/admin/laporan-kehadiran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/laporan-kehadiran/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/laporan-kehadiran/print">> = Specific
  const handler = {} as typeof import("../../src/app/admin/laporan-kehadiran/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/monitor_perusahaan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitor_perusahaan">> = Specific
  const handler = {} as typeof import("../../src/app/admin/monitor_perusahaan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/notifikasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifikasi">> = Specific
  const handler = {} as typeof import("../../src/app/admin/notifikasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pengumuman/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pengumuman">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pengumuman/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/positions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/positions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/positions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/rekap-kehadiran-karyawan/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rekap-kehadiran-karyawan/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/rekap-kehadiran-karyawan/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/rekap-kehadiran-karyawan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rekap-kehadiran-karyawan">> = Specific
  const handler = {} as typeof import("../../src/app/admin/rekap-kehadiran-karyawan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/shifts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/shifts">> = Specific
  const handler = {} as typeof import("../../src/app/admin/shifts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/work-schedules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/work-schedules">> = Specific
  const handler = {} as typeof import("../../src/app/admin/work-schedules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/beranda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beranda">> = Specific
  const handler = {} as typeof import("../../src/app/beranda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cuti/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuti">> = Specific
  const handler = {} as typeof import("../../src/app/cuti/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/history/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/history/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../src/app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifikasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifikasi">> = Specific
  const handler = {} as typeof import("../../src/app/notifikasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pengumuman/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pengumuman">> = Specific
  const handler = {} as typeof import("../../src/app/pengumuman/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/presensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/presensi">> = Specific
  const handler = {} as typeof import("../../src/app/presensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profil">> = Specific
  const handler = {} as typeof import("../../src/app/profil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/attendance-reports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/attendance-reports/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/attendance-reports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/attendance-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/attendance-reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/attendance-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/departments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/departments">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/departments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/employee-attendance-recap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/employee-attendance-recap">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/employee-attendance-recap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/jabatans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/jabatans">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/jabatans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/leave-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/leave-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/leave-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/monitor-perusahaan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/monitor-perusahaan">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/monitor-perusahaan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/office-locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/office-locations">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/office-locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/offices/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/offices/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/offices/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/offices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/offices">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/offices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/positions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/positions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/positions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/shifts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shifts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/shifts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/work-schedules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/work-schedules">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/work-schedules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/[id]/photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/[id]/photo">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/[id]/photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/check-in/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/check-in">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/check-in/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/check-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/check-out">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/check-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attendance/today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/today">> = Specific
  const handler = {} as typeof import("../../src/app/api/attendance/today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geocode/reverse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geocode/reverse">> = Specific
  const handler = {} as typeof import("../../src/app/api/geocode/reverse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leave-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leave-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/leave-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/offices/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/offices/active">> = Specific
  const handler = {} as typeof import("../../src/app/api/offices/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profil/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profil/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/profil/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profil/photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profil/photo">> = Specific
  const handler = {} as typeof import("../../src/app/api/profil/photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profil/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profil">> = Specific
  const handler = {} as typeof import("../../src/app/api/profil/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
