var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/laporan-kehadiran/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1bioe_c._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1gsjpr5.js")
R.c("server/chunks/ssr/[root-of-the-server]__13dnbfs._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ekapvg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_laporan-kehadiran_page_actions_11hyivi.js")
R.m(34009)
module.exports=R.m(34009).exports
