var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/monitor_perusahaan/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hkz-s_._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0724cyn.js")
R.c("server/chunks/ssr/[root-of-the-server]__13dnbfs._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ekapvg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_monitor_perusahaan_page_actions_0mbsysn.js")
R.m(14605)
module.exports=R.m(14605).exports
