var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/cuti/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1e_r7ya._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0pflfv0.js")
R.c("server/chunks/ssr/[root-of-the-server]__13dnbfs._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ekapvg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_cuti_page_actions_02vyzfi.js")
R.m(93093)
module.exports=R.m(93093).exports
